require 'huginn_agent'

#HuginnAgent.load 'huginn_ipinfo_abuse_contact_data_agent/concerns/my_agent_concern'
HuginnAgent.register 'huginn_ipinfo_abuse_contact_data_agent/ipinfo_abuse_contact_data_agent'
